### PR TITLE
Configurable mapping

### PR DESCRIPTION
**Pull request by haacked**
This is a PR for #27. Just look at the last commit as I based this on my other branch. I'll rebase this against master when those other changes are merged. :)

I went with the virtual method approach since the delegate syntax is so godawful. :stuck_out_tongue:

### CODE REVIEW

**Comment by prabirshrestha** [comment]
needs rebase

**Comment by haacked** [comment]
Rebased and also added more `GeneratedCodeAttribute`s to simple-json.

**Comment by prabirshrestha** [comment]
could you also put `[GeneratedCodeAttributes]` in `PocoJsonSerializerStrategy` so it is consistent.

**Comment by haacked** [comment]
Can't believe I missed that.

**Comment by haacked** [comment]
Oh, and done!

**Comment by prabirshrestha** [comment]
pushed https://nuget.org/packages/SimpleJson/0.25.0

**Pull request merged**
