### PR TITLE
Codeanalysis fixes

### PR DESCRIPTION
**Pull request by haacked**
This includes the commit from my other PR. You can ignore that one if you accept this one. 

In this one, I fixed a few Code Analysis performance rules by removing unnecessary casts. I tried to do the minimal amount of work to satisfy the rules. I think there's definitely some more refactoring worth doing later. :)

Also fixed a few design rules. Minor stuff. All tests continue to pass.

### CODE REVIEW

**Comment by haacked** [comment]
Ah, ok. Maybe you should make the copy of ReflectionUtils part of the build. :)

**Comment by haacked** [comment]
Actually, it should probably be a submodule. Are you familiar with git submodules?

**Comment by haacked** [comment]
OR (sorry for the spam) make it a nuget package that deploys a .cs file and make Simple.Json depend on it. At the end of the day, it's the same result other than it's 2 files being added to and compiled into a project rather than one.

**Comment by haacked** [comment]
Ok, I made all the changes you requested. I did it in a new commit to make it easy to review. If you'd prefer me to rebase code review changes into the original commits on my branch before you merge, let me know.

**Comment by prabirshrestha** [comment]
needs rebase

**Comment by haacked** [comment]
I'm going to close this one and put it all in my other PR. Fine with you?

**Comment by prabirshrestha** [comment]
i'm fine with it

**Pull request closed without merging**
